### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ramnamaqsood** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#6]
Hello!! You did great work on anomaly detection. Could you please provide me with training annotation that you used in this code and kindly also tell me that how you label frames in your code. Waiting for your reply

**Comment by 1xabhay** [comment]
There are no temporal annotations available or required for this approach. The architecture is based on Multiple Instance Learning,  Instead of receiving a set of instances which are individually labeled, the learner receives a set of labeled bags, each containing many instances. In the simple case of multiple-instance binary classification, a bag may be labeled negative if all the instances in it are negative. 

_https://en.wikipedia.org/wiki/Multiple_instance_learning_
